### ISSUE TITLE
Why not throw an Error?

### ISSUE THREAD

**Issue by tejasmanohar** [simplyianm/koa-joi-schema#1]
Why [write to `ctx`](https://github.com/simplyianm/koa-joi-schema/blob/master/index.js#L14) when you can throw an actual `Error` that's catchable and has additional details? If you're looking for an example, see what I wrote for [trie-router](https://github.com/koajs/trie-router) [here](https://github.com/koajs/trie-router/blob/master/test/routes.js#L188-#L209)— it's also a validation error of sorts.

**Comment by tejasmanohar** [comment]
I'd recommend throwing one with a `status` of 400. This way, it can be caught and re-thrown by the developer using your module in an upstream middleware. [http-errors](https://www.npmjs.com/package/http-errors) is a nice module for this, but there's also [errors](https://www.npmjs.com/package/http-errors), which is a bit bulkier but more flexible if you want to be able to `instanceof` the errors to the specific case like `KoaJoiValidationError`.

**Comment by macalinao** [comment]
I don't like `instanceof`. I'll just throw the Joi error directly. I'm updating the example right now.

**Comment by macalinao** [comment]
See https://github.com/simplyianm/koa-joi-schema/commit/f6d9711468cdc46f436a643088c5819dec9a173d for updates.

**Comment by tejasmanohar** [comment]
@simplyianm Well, throwing the Joi error sounds like a fair design decision, but why don't you like `instanceof`? Error `code`s often have collisions within an application when you're trying to identify them in a `catch` block if they're not unique enough and names... even better, as it appears Joi calls them [`ValidationError`](https://github.com/hapijs/joi/blob/master/lib/errors.js#L141)s (I wonder if any other modules use that error?) :P

**Comment by macalinao** [comment]
I doubt there would be a significant collision in ValidationError, but you could always duck-type and check for properties like details, etc.

**Comment by macalinao** [comment]
I don't use instanceof because Joi doesn't.

**Comment by tejasmanohar** [comment]
@simplyianm If I recall, that's the same name [Mongoose](https://github.com/Automattic/mongoose) uses for its Validation errors... it doesn't even say Joi in it, I predict significant collision. Thankfully, Mongoose throws custom Error objects so I never depend on the `name` but rather `instanceof` :)

**Comment by tejasmanohar** [comment]
@simplyianm Surely, you can catch Joi's error, wrap its details in a custom Error object, and re-throw it.

**Comment by macalinao** [comment]
ahahaha you're right. Please see https://github.com/simplyianm/koa-joi-schema/commit/45e7cb48927c9ed06816f5127a8cf6412c22629f

**Comment by tejasmanohar** [comment]
@simplyianm Aha, http://stackoverflow.com/questions/15012250/handling-mongoose-validation-errors-where-and-how - Mongoose throws errors with the name `ValidatorError`, not `ValidationError`, but that is a clear example of how easy it is to cause collision when you're depending on a generic name.

UPDATE: I think `ValidatorError`s are for custom path validators and `ValidationError`s are for built-in validations in mongoose, can't remember.

**Comment by tejasmanohar** [comment]
@simplyianm Well... that's still super hacky. `details` is another super common field for errors... and its often an error (especially for validation errors). That said, you lucked out on Mongoose this time though since it uses `errors`, not `details`... but either way, would def recommend custom objects to prevent collisions altogether. That's the only fault-proof way to do it afaik.

**Comment by tejasmanohar** [comment]
oh and don't forget to expose an error from your module so others can require and `instanceof`

**Comment by tejasmanohar** [comment]
... ok i guess `JoiValidationError` is a better name but not as great as `instanceof` imo 2571d4c481b194bc41999c14aa00c2e9e4054838
