### ISSUE TITLE
Expose Joi

### ISSUE THREAD

**Issue by tejasmanohar** [simplyianm/koa-joi-schema#2]
I recommend you expose Joi from the module to avoid version conflicts with some validations passing in the middleware but not passing somewhere else in the application. See how [koa-joi-router](https://github.com/pebble/koa-joi-router) does it [here](https://github.com/pebble/koa-joi-router#module-properties). You won't be forcing any version of Joi on the user of this module, but you also give them an easy option rather than having to keep track of what version this module uses over the course of upgrades.

**Comment by macalinao** [comment]
i do.

**Comment by macalinao** [comment]
https://github.com/simplyianm/koa-joi-schema/blob/master/index.js#L18

**Comment by tejasmanohar** [comment]
Oh, my bad. Missed that.

**Comment by macalinao** [comment]
You're looking with your mouth, not your eyes.

**Comment by tejasmanohar** [comment]
Lol wow harsh :P
